### ISSUE TITLE
0.3.1 Release request

### ISSUE THREAD

**Issue by folix-01** [collective/collective.sentry#23]
Is it possible to have a minor release with the last changes?

**Comment by mauritsvanrees** [comment]
I don't have PyPI rights.  Gil, and @zopyx and @thomasmassmann have that.

If someone grants ownership to the `collective` user (or to the group) I could make a release.

**Comment by zopyx** [comment]
Done

**Comment by gforcada** [comment]
Sorry, lots of things after the conference, release done ✨

**Comment by mauritsvanrees** [comment]
Thanks.
